import { Geist, Geist_Mono, Newsreader, Red_Hat_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  weight: ['200'],
  subsets: ["latin"],
})

const redHatMono = Red_Hat_Mono({
  variable:"--font-red-hat-mono",
  subsets:["latin"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${newsreader.variable} ${redHatMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
